# Generated by Django 5.1.4 on 2026-09-17 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('technology', models.CharField(choices=[('SLA', 'Stereolithography (SLA)'), ('SLS', 'Selective Laser Sintering (SLS)')], max_length=10)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('printing', 'Printing'), ('maintenance', 'Maintenance')], default='idle', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(choices=[('resin_standard', 'Standard resin (SLA)'), ('resin_tough', 'Tough resin (SLA)'), ('resin_castable', 'Castable resin (SLA)'), ('nylon_pa12', 'Nylon PA12 (SLS)'), ('nylon_glass_filled', 'Glass-filled nylon (SLS)')], max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quote_pending', 'Quote pending'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('printing', 'Printing'), ('post_processing', 'Post-processing'), ('qc', 'Quality control'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('reprint', 'Queued for reprint')], default='quote_pending', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_lead_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.part')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('quote_pending', 'Quote pending'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('printing', 'Printing'), ('post_processing', 'Post-processing'), ('qc', 'Quality control'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('reprint', 'Queued for reprint')], max_length=20)),
                ('to_status', models.CharField(choices=[('quote_pending', 'Quote pending'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('printing', 'Printing'), ('post_processing', 'Post-processing'), ('qc', 'Quality control'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('reprint', 'Queued for reprint')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_customer_idx'),
        ),
    ]
